Us20 securisation
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Moovit pull request #11
Opened 2024-06-26 14:55 UTC by Hamsolovski

2024-06-26 14:56 UTC, WildAntho approved these changes

2024-06-26 15:23 UTC, VinchC approved these changes

2024-06-26 15:29 UTC, Alexandre78R requested changes

2024-06-26 15:29 UTC, Alexandre78R commented on server/app/controllers/templateActions.js
> +    res.status(201).json(template);
Please changed port 200 (GET)

2024-06-26 15:29 UTC, Alexandre78R commented on server/app/controllers/trainingActions.js
>      res.status(201).json(newTraining);
Please changed port 200 (GET)

2024-06-28 12:53 UTC, Alexandre78R approved these changes
Good

2024-06-28 12:54 UTC, merged