Bugfix page refresh on change
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Moovit pull request #12
Opened 2024-06-26 15:18 UTC by Hamsolovski

2024-06-26 15:24 UTC, WildAntho approved these changes

2024-06-26 15:30 UTC, Brian-boudrioux requested changes

2024-06-26 15:30 UTC, Brian-boudrioux commented on server/app/controllers/templateActions.js
> +    res.status(201).json(template);
201 is for new created ressource you should return a 200 status code there

2024-06-28 12:54 UTC, Alexandre78R approved these changes
Good

2024-06-28 12:54 UTC, merged