Bugfix page mask detail button when empty
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Moovit pull request #15
Opened 2024-07-02 15:06 UTC by Hamsolovski

2024-07-02 15:08 UTC, WildAntho approved these changes

2024-07-03 07:15 UTC, Alexandre78R approved these changes
Good

2024-07-03 07:17 UTC, Alexandre78R requested changes

2024-07-03 07:17 UTC, Alexandre78R commented on client/src/pages/TemplateDetails/templateDetails.css
> +.templatedetail-logo-type {
template-detail ?

2024-07-03 07:17 UTC, Alexandre78R commented on client/src/pages/TemplateDetails/templateDetails.css
> +.templatedetail-title {
template-detail ?

2024-07-03 07:17 UTC, Alexandre78R reviewed
.

2024-07-09 12:12 UTC, merged