Several bugs fixed
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Moovit pull request #16
Opened 2024-07-04 15:25 UTC by WildAntho

2024-07-05 14:02 UTC, Hamsolovski approved these changes

2024-07-09 12:19 UTC, Alexandre78R requested changes

2024-07-09 12:19 UTC, Alexandre78R commented on client/src/components/Background/Background.jsx
Modify span boucle logic

2024-07-09 12:26 UTC, VinchC approved these changes

2024-07-09 12:26 UTC, merged