Us14 feedback
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Moovit pull request #6
Opened 2024-06-19 10:16 UTC by WildAntho

2024-06-20 07:17 UTC, Hamsolovski commented on client/src/components/Feedback/Feedback.jsx
C'EST LONG

2024-06-20 07:19 UTC, Hamsolovski approved these changes
All Good !

2024-06-20 14:34 UTC, Alexandre78R requested changes

2024-06-20 14:34 UTC, Alexandre78R commented on client/src/components/Card/Card.jsx
> +// const api = import.meta.env.VITE_API_URL;
Delete code dead

2024-06-20 14:34 UTC, Alexandre78R commented on client/src/components/Feedback/Feedback.jsx
?

2024-06-20 14:34 UTC, Alexandre78R commented on client/src/components/Feedback/Feedback.jsx
> +      console.error("erreur");
delete console.error usless

2024-06-20 14:34 UTC, Alexandre78R commented on client/src/components/Feedback/Feedback.jsx
> +            console.error("erreur client");
error handling please 👍

2024-06-20 14:34 UTC, Alexandre78R commented on client/src/components/Feedback/Feedback.jsx
> +            console.error("erreur client");
error handling please 👍

2024-06-20 14:34 UTC, Alexandre78R commented on client/src/components/Feedback/Feedback.jsx
> +      console.error("erreur");
error handling please?

2024-06-20 14:34 UTC, Alexandre78R commented on client/src/components/Feedback/Feedback.jsx
> +        console.error(error);
error handling please 👍

2024-06-20 14:34 UTC, Alexandre78R commented on client/src/components/TipsCard/TipsCard.jsx
> +/* eslint-disable react/require-default-props */
No Authorized

2024-06-20 14:34 UTC, Alexandre78R commented on client/src/pages/Journal/Journal.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Not authorized

2024-06-20 14:34 UTC, Alexandre78R commented on server/app/controllers/feedbackActions.js
> +            res.json(result);
Please switch port edit

2024-06-20 14:34 UTC, Alexandre78R commented on server/app/controllers/feedbackActions.js
> +            res.json(result);
( 204 )

2024-06-20 15:26 UTC, Hamsolovski approved these changes

2024-06-21 07:49 UTC, Alexandre78R approved these changes

2024-06-21 07:50 UTC, merged